name: Build RPCS3 MSYS2
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
          - uses: actions/checkout@v4
            with:
              submodules: recursive
              fetch-depth: 0  # Ensures it gets the full history for SHA checks

          - uses: msys2/setup-msys2@v2
            with:
              msystem: UCRT64
              update: true
              install: >-
                mingw-w64-ucrt-x86_64-gcc 
                mingw-w64-ucrt-x86_64-cmake 
                mingw-w64-ucrt-x86_64-ninja 
                mingw-w64-ucrt-x86_64-qt6-base 
                mingw-w64-ucrt-x86_64-sdl3
                mingw-w64-ucrt-x86_64-vulkan-loader
                mingw-w64-ucrt-x86_64-yasm
                git

          - name: Build
            shell: msys2 {0}
            run: |
              # Force FFmpeg submodule update if the prebuilt check fails
              git submodule update --init --recursive
              mkdir build && cd build
              cmake -G Ninja .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DUSE_SYSTEM_SDL=ON \
                -DUSE_NATIVE_INSTRUCTIONS=OFF
              ninja rpcs3

